/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as ReportRouteImport } from './routes/report'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DataRouteImport } from './routes/data'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/data': typeof DataRoute
  '/dev': typeof DevRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/score': typeof ScoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/data': typeof DataRoute
  '/dev': typeof DevRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/score': typeof ScoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/data': typeof DataRoute
  '/dev': typeof DevRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/score': typeof ScoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/data'
    | '/dev'
    | '/history'
    | '/report'
    | '/score'
    | '/sitemap.xml'
    | '/tasks'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/data'
    | '/dev'
    | '/history'
    | '/report'
    | '/score'
    | '/sitemap.xml'
    | '/tasks'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/data'
    | '/dev'
    | '/history'
    | '/report'
    | '/score'
    | '/sitemap.xml'
    | '/tasks'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  DataRoute: typeof DataRoute
  DevRoute: typeof DevRoute
  HistoryRoute: typeof HistoryRoute
  ReportRoute: typeof ReportRoute
  ScoreRoute: typeof ScoreRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasksRoute: typeof TasksRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  DataRoute: DataRoute,
  DevRoute: DevRoute,
  HistoryRoute: HistoryRoute,
  ReportRoute: ReportRoute,
  ScoreRoute: ScoreRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasksRoute: TasksRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
